name: Update WakaTime Stats

on:
  schedule:
    # Runs every day at 7 AM UTC
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: WakaTime Readme Stats
      uses: anmol098/waka-readme-stats@master
      with:
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        SHOW_PROJECTS: "False"
        SHOW_PROFILE_VIEWS: "False"
        SHOW_DAYS_OF_WEEK: "False"
        SHOW_TIMEZONE: "False"
        SHOW_EDITORS: "False"
        SHOW_LANGUAGE_PER_REPO: "False"
        SHOW_COMMIT: "False"
        SHOW_LINES_OF_CODE: "False"
        SHOW_LOC_CHART: "False"